#!/bin/bash


####################################################
#                 Music_Finder V0.1                #
#  https://github.com/hessamashari/video-tool.git  #
####################################################


normal="$(printf '\033[0m')"          # text mode
# Colors
red="$(printf '\033[0;31m')"  		  # red
green="$(printf '\033[0;32m')"        # green
orange="$(printf '\033[0;33m')"       # orange
blue="$(printf '\033[0;34m')"         # blue
white="$(printf '\033[0;37m')"        # white

# ----------\Main function\----------
function main() {
	echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"
	read -p "${green}What can i do for you ???${normal}
	1)${orange} Reduce video size.${normal}
	2)${orange} Change the video format.${normal}

	Enter the number of the option that you selected : " selectedItem
	echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"
	if [[ "$selectedItem" == "1" ]]; then
		select_video_path
	elif [[ "$selectedItem" == "2" ]]; then
		echo "helo"
	else
		echo -e "${red}Invalid argument!${normal}"
		exit 1
	fi
}

# ----------\Select movie function\----------
function select_video_path() {
	# Ask for video path
	read -p "Do you want to search video for you {search / s} or you know the video location {location / l} : " searchVideoAnswer
	echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"

	if [[ "$searchVideoAnswer" == "search" || "$searchVideoAnswer" == "S" || "$searchVideoAnswer" == "s" ]]; then
		read -p "Do you like to serach all of your system (Requires root access)? [Y/n] " searchAllSystem

		if [[ "$searchAllSystem" == "" || "$searchAllSystem" == "y" || "$searchAllSystem" == "Y" ]]; then
			# Search all of file system
		    echo -e "This operation may take a while!"

		elif [[ "$searchAllSystem" == "n" || "$searchAllSystem" == "N" ]]; then
			read -p "Do you like search this directory? [Y/n] " workingDirectory

			if [[ "$workingDirectory" == "" || "$workingDirectory" == "y" || "$workingDirectory" == "Y" ]]; then
				# Search current directory
	elif [[ "$searchVideoAnswer" == "location" || "$searchVideoAnswer" == "L" || "$searchVideoAnswer" == "l" ]]; then
		# Read path/to/video
		read -p "Enter path of the video : " -i "" -e videoPath
	else
		echo -e "${red}Invalid argument!${normal}"
	fi
}

# ----------\Reduce video size function\----------
function reduce_video_size() {
	echo "hello"
}

# ----------\Help function\----------
function usage() {
	echo -e "\n Usage: video-tool [ -h | --help ],  [ --uninstall ],   [ -U | --update ]"
	return
}

# ----------\Input options\----------
case "$1" in
    "")    main    ;;
    "--update" | "-U")    update    ;;
	"--uninstall")    uninstall    ;;
	"--help" | "-h")    usage    ;;
	*)    usage    ;;
esac
exit 0
