#!/bin/bash


# Timeline

# v0.1 --(20180815) add reduce_video_size function
# v0.2 --(20180816) add convert_video_format function
# v0.3 --(20180816) add show_version and uninstall function
# v0.4 --(20180816) add update function and installer script
# v0.5 --(20180828) add src and src/main directories and move functions to them
# v0.6 --(20180904) add join file for joining videos

# author : Hessam Ashari
# license: GPLv3
# gitlab : https://gitlab.com/hessam.ashari/video-tool
# github : https://github.com/hessamashari/video-tool
# Email  : hessam.ashari@gmail.com
#
# requirement : ffmpeg,git
#
# This file is part of Video_Tool.
#
# Video_Tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Video_Tool is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

normal="$(printf '\033[0m')"          # text mode
# Colors
red="$(printf '\033[0;31m')"  		  # red
green="$(printf '\033[0;32m')"        # green
orange="$(printf '\033[0;33m')"       # orange
blue="$(printf '\033[0;34m')"         # blue
white="$(printf '\033[0;37m')"        # white

# Import functions
source src/main/select.sh
source src/main/update.sh
source src/main/uninstall.sh
source src/join.sh

# ---------- Main function ----------
main() {
    clear

    echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"
    read -p "${green}What can I do for you ???${normal}
        1)${orange} Reduce video size.${normal}
        2)${orange} Convert video format.${normal}
        3)${orange} Join videos.${normal}
        4)${orange} Mute a video.${normal}
        5)${orange} Extract the audio from video.${normal}
        6)${orange} Cut video into a smaller clip.${normal}
        7)${orange} Convert a video into animated GIF.${normal}

    Enter the number of the option that you selected : " selectedItem
    echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"

    # Check the given number is greater than options or not
    if [[ "$selectedItem" -gt "0" && "$selectedItem" -lt "8" ]]; then
        if [[ "$selectedItem" == "3" ]]; then
            join_videos
        else
            select_video_path
        fi
    else
        echo -e "${red}Invalid argument!${normal}"
        exit 1
    fi
}

# ---------- Show version function ---------
show_version() {
    echo -e "\n"
	cat <<- EOF
	Video_Tool, version v0.8 (x86_64-unknown-linux-gnu)
	Copyright (C) 2018 Hessam Ashari.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

	built with bash 4.4.23 (GNU/bash)
    EOF
    return
}

# ---------- Show help function ----------
usage() {
    echo -e "\n"
    echo -e " Usage: video-tool [ -H | --help ]  [ -V | --version ]  [ --uninstall ]  [ -U | --update ]"
    return
}

# ---------- Input options ----------
case "$1" in
    "")    main    ;;
    "--update" | "-U")    update    ;;
    "--uninstall")    uninstall    ;;
    "--help" | "-H")    usage    ;;
    "--version" | "-V")    show_version    ;;
    *)    usage    ;;
esac;
exit 0
